---
version: '3'

networks:
  pennix:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    networks:
      - pennix

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - '3306:3306'
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+8:00'
      ]
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=exporter
      - MYSQL_PASSWORD=Prometheus
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - pennix

  mysqld_exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysqld_exporter
    ports:
      - '9104:9104'
    environment:
      - DATA_SOURCE_NAME=exporter:Prometheus@(mysql:3306)/
    volumes:
      - ./mysql-exporter/.my.cnf:/.my.cnf
    depends_on:
      - mysql
    networks:
      - pennix

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    hostname: node_exporter
    ports:
      - '9100:9100'
    networks:
      - pennix

  grafana:
    image: grafana/grafana
    container_name: grafana
    entrypoint:
      - /usr/share/grafana/bin/grafana-server
      - --homepath=/usr/share/grafana
      - --config=/etc/grafana-config/grafana.ini
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana/config:/etc/grafana-config
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - pennix
    depends_on:
      - prometheus
      - mysqld_exporter
      - node-exporter
