---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["10.102.11.140:9090"]
  - job_name: 'mysql'
    static_configs:
      - targets: ["10.102.11.140:9104"]
  - job_name: 'node'
    static_configs:
      - targets: ["10.102.11.140:9100"]