# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://10.102.11.140:9090 
  isDefault: true
  access: proxy
  editable: true